### ISSUE TITLE
Please add the possibility to use links to preselected blockchain and token options

### ISSUE THREAD

**Issue by mexiweb3** [bandohq/docs#19]
Va de nuevo

Please add the possibility to use links to preselected blockchain and token options

**Comment by domix** [comment]
I'm closing this issue because it is not the right place for it. I moved your previous issue to the BandoReact repository.

https://github.com/bandohq/react-bando/issues/200

This repository is for documentation. Requests for features can be added over there.

Thank you very much @mexiweb3
